name: Deploy Azure Function App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Archive function app
      run: |
        mkdir -p deployment
        cp -r function.json host.json __init__.py requirements.txt deployment/
        cd deployment
        zip -r ../functionapp.zip .
        cd ..

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set active Azure subscription
      run: |
        az account set --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"

    - name: Azure CLI Script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az functionapp deployment source config-zip \
          --resource-group pawait_group \
          --name one-drive-function \
          --src functionapp.zip

    - name: Azure PowerShell Script
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          $ErrorActionPreference = "Stop"

          # Connect to Azure using service principal credentials
          Connect-AzAccount -ServicePrincipal -TenantId ${{ secrets.AZURE_TENANT_ID }} -ApplicationId ${{ secrets.AZURE_CLIENT_ID }} -Credential (New-Object System.Management.Automation.PSCredential(${{ secrets.AZURE_CLIENT_ID }}, (ConvertTo-SecureString ${{ secrets.AZURE_CLIENT_SECRET }} -AsPlainText -Force)))
          
          # Set Azure context to the specified subscription
          Set-AzContext -SubscriptionId ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
          # Deploy Azure Function App
          Set-AzFunctionApp -ResourceGroupName "pawait_group" -Name "one-drive-function" -ArchivePath "functionapp.zip"
